version: "3.8"

services:
  todo_list:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_URI=${DB_URI}
      - DATABASE=${DATABASE_NAME}
    ports:
     - 8060:${PORT}
    healthcheck:
      test: "wget --spider ${HOST}:${PORT}/health"
      interval: 15s
      retries: 10
    depends_on:
      - mongo
  mongo:
    build:
      context: dev_tools/mongo_docker
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
